version: '3.7'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - '5432:5432'
    volumes:
      - agent-db:/var/lib/postgresql/data

  agent:
    image: marko131/devops:latest
    build:
      context: .
    environment:
      DATABASE_TYPE: postgres
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE: devops
      IMAGE_DIR: /var/tmp
    depends_on:
      - postgres
    ports:
      - '8080:8080'

volumes:
  agent-db:
