name: Production

on:
  push:
    branches:
      - main
      - mm-prod-cd--26

jobs:
  pre-staging:
    name: Publish Docker images and deploy to production
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.5
        with:
          release_branches: main
          default_bump: minor
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create a GitHub release
        uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          release_name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}

      - name: Build docker images
        run: ./buildImages.sh ${{ steps.tag_version.outputs.new_tag }} ${{ secrets.MILAN_DOCKERHUB_USERNAME }} ${{ secrets.MILAN_DOCKERHUB_PASSWORD }}

      - name: Deploy to prod env on Heroku
        run: ./deploy.sh ${{ steps.tag_version.outputs.new_tag }} markostanic222@gmail.com ${{secrets.MARKO_HEROKU_API_KEY}} prod-tim7-terraform-backend ${{secrets.TOKEN_SECRET}} prod
